'use client';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type Konva from 'konva';
import Toolbar from './Toolbar/Toolbar';
import CanvasStage from './CanvasEditor/CanvasStage';
import PropertiesPanel from './PropertiesPanel/PropertiesPanel';
import CanvasList from './CanvasList/CanvasList';
import { api, type CanvasDocument, type CanvasElement, type ElementType } from '../services/api';

const initial: CanvasDocument = { name: 'Untitled composition', width: 1000, height: 620, elements: [] };
const uid = () => `element-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
export default function Editor() { const [canvas, setCanvas] = useState<CanvasDocument>(initial); const [selectedId, setSelectedId] = useState<string | null>(null); const [canvases, setCanvases] = useState<CanvasDocument[]>([]); const [history, setHistory] = useState<CanvasElement[][]>([]); const [future, setFuture] = useState<CanvasElement[][]>([]); const [saving, setSaving] = useState(false); const [status, setStatus] = useState('All changes saved'); const stageRef = useRef<Konva.Stage | null>(null); const skipHistory = useRef(false);
  useEffect(() => { api.list().then(setCanvases).catch(() => setStatus('API unavailable — changes are local')); }, []);
  const updateElements = useCallback((next: CanvasElement[]) => { setHistory((h) => [...h.slice(-29), canvas.elements]); setFuture([]); setCanvas((c) => ({ ...c, elements: next })); setStatus('Unsaved changes'); }, [canvas.elements]);
  const changeElement = (id: string, patch: Partial<CanvasElement>) => { if (skipHistory.current) return; updateElements(canvas.elements.map((el) => el.id === id ? { ...el, ...patch } : el)); };
  const addElement = (type: ElementType) => { const base = { id: uid(), x: 160 + canvas.elements.length * 18, y: 130 + canvas.elements.length * 16, rotation: 0, fill: type === 'text' ? '#1d1b24' : type === 'circle' ? '#ff8a5b' : '#8b5cf6' }; const element: CanvasElement = type === 'rectangle' ? { ...base, type, width: 190, height: 120 } : type === 'circle' ? { ...base, type, radius: 68 } : { ...base, type, text: 'Hello canvas', fontSize: 32 }; updateElements([...canvas.elements, element]); setSelectedId(element.id); };
  const updateCanvas = (patch: Partial<CanvasDocument>) => { setCanvas((c) => ({ ...c, ...patch })); setStatus('Unsaved changes'); };
  const save = useCallback(async () => { setSaving(true); try { const saved = canvas._id ? await api.update(canvas._id, canvas) : await api.create(canvas); setCanvas(saved); setCanvases((old) => [saved, ...old.filter((c) => c._id !== saved._id)]); setStatus('Saved just now'); } catch (e) { setStatus(e instanceof Error ? e.message : 'Unable to save'); } finally { setSaving(false); } }, [canvas]);
  useEffect(() => { if (status !== 'Unsaved changes') return; const timer = setTimeout(save, 1200); return () => clearTimeout(timer); }, [status, save]);
  const undo = () => { const previous = history.at(-1); if (!previous) return; skipHistory.current = true; setFuture((f) => [...f, canvas.elements]); setCanvas((c) => ({ ...c, elements: previous })); setHistory((h) => h.slice(0, -1)); setTimeout(() => { skipHistory.current = false; }, 0); setStatus('Unsaved changes'); };
  const redo = () => { const next = future.at(-1); if (!next) return; skipHistory.current = true; setHistory((h) => [...h, canvas.elements]); setCanvas((c) => ({ ...c, elements: next })); setFuture((f) => f.slice(0, -1)); setTimeout(() => { skipHistory.current = false; }, 0); setStatus('Unsaved changes'); };
  const selected = useMemo(() => canvas.elements.find((e) => e.id === selectedId), [canvas.elements, selectedId]);
  const removeSelected = () => { if (selectedId) { updateElements(canvas.elements.filter((e) => e.id !== selectedId)); setSelectedId(null); } };
  const reorder = (direction: number) => { if (!selectedId) return; const index = canvas.elements.findIndex((e) => e.id === selectedId); const target = index + direction; if (target < 0 || target >= canvas.elements.length) return; const next = [...canvas.elements]; [next[index], next[target]] = [next[target], next[index]]; updateElements(next); };
  const load = async (id: string) => { try { const doc = await api.get(id); setCanvas(doc); setSelectedId(null); setHistory([]); setFuture([]); setStatus('All changes saved'); } catch (e) { setStatus(e instanceof Error ? e.message : 'Unable to load'); } };
  const removeCanvas = async (id: string) => { try { await api.remove(id); setCanvases((old) => old.filter((c) => c._id !== id)); if (canvas._id === id) newCanvas(); } catch (e) { setStatus(e instanceof Error ? e.message : 'Unable to delete'); } };
  const newCanvas = () => { setCanvas({ ...initial, name: 'Untitled composition', elements: [] }); setSelectedId(null); setHistory([]); setFuture([]); setStatus('Unsaved changes'); };
  const exportPng = () => { const uri = stageRef.current?.toDataURL({ pixelRatio: 2 }); if (!uri) return; const link = document.createElement('a'); link.download = `${canvas.name.replace(/\s+/g, '-').toLowerCase()}.png`; link.href = uri; link.click(); };
  return <main className="app-shell"><Toolbar onAdd={addElement} onNew={newCanvas} onSave={save} onExport={exportPng} onUndo={undo} onRedo={redo} canUndo={history.length > 0} canRedo={future.length > 0} saving={saving} /><div className="workspace"><aside className="left-rail"><div className="document-heading"><span className="eyebrow">Current file</span><input value={canvas.name} onChange={(e) => updateCanvas({ name: e.target.value })} /><div className="save-state"><span className={status === 'Unsaved changes' ? 'dot unsaved' : 'dot'} />{status}</div></div><CanvasList canvases={canvases} activeId={canvas._id} onLoad={load} onDelete={removeCanvas} /></aside><section className="stage-area"><div className="stage-topline"><div><span className="eyebrow">Canvas / {canvas.name}</span><h1>Make something <em>worth seeing.</em></h1></div><div className="canvas-size">{canvas.width} <span>×</span> {canvas.height}</div></div><div className="stage-wrap"><div className="stage-board"><CanvasStage width={canvas.width} height={canvas.height} elements={canvas.elements} selectedId={selectedId} onSelect={setSelectedId} onChange={changeElement} stageRef={stageRef} /></div></div><div className="hint"><span>⌘</span> Select an element to transform it <span className="hint-divider" /> Drag to move · Corner handles to resize · Top handle to rotate</div></section><PropertiesPanel element={selected} onChange={(patch) => selectedId && changeElement(selectedId, patch)} onDelete={removeSelected} onForward={() => reorder(1)} onBackward={() => reorder(-1)} /></div></main>; }
